### ISSUE TITLE
Problème lors du calcul de la jacobienne

### ISSUE THREAD

**Issue by lmoeneclaey** [lmoeneclaey/Projet_Maths_Info#1]
Cf Projet.py @boisgera

**Comment by lmoeneclaey** [comment]
C'est lors de l'utilisation du module autograd, le programme nécessite un tableau à la place d'un scalaire: j'ai donc une erreur de type IndexError: invalid index to scalar variable.

**Comment by boisgera** [comment]
J'ai exécuté le notebook sans erreur. J'ai également exécuté le programme Python `Projet.py` avec la commande

    $ python Projet.py

dans un terminal (c'est peu ou prou l'équivalent du `runfile` que fait Spyder), mais je n'ai pas non plus d'erreur. Donc à ce stade, je n'arrive pas à reproduire l'erreur. Mais ceci dit, le fichier `Projet.py` semble *définir* des fonctions, pas exécuter leur code, il y manque peut-être le bout de code qui va générer l'erreur.

**Comment by lmoeneclaey** [comment]
Oui pardon, il faut y rajouter ceci :

    a = [0.0, 0.5, 1.5, 1.0, -1.5, -1.0, -0.5]
    for i in a:
        resultats = contour(f, i,[-2.0,-1.0,0.0,1.0,2.0,3.0],[-2.0,-1.0,0.0,1.0,2.0,3.0])
        for x, y in resultats:
            plt.plot(x, y, i)
    plt.show()

**Comment by boisgera** [comment]
Première démarche : simplifier progressivement le "code client" pour avoir le code utilisant le moins de fonctionnalités possibles mais qui produise encore l'erreur pour faciliter la localisation du problème. Pour le moment, je constate que l'usage de matplotlib, l'appel de différents niveaux de lignes de contours, le découpage en cellules de `contour` ne sont pas en cause : le code 

    resultats = simple_contour(f, 0.0)

produit le même type d'erreur.

**Comment by boisgera** [comment]
L'examen de la trace de l'erreur montre qu'autograd flanche quand vous voulez calculer le jacobien de `F`. Et `F` a un problème : les mêmes noms `x` et `y` sont utilisés pour désigner les arguments de la fonction (des flottants) et les tableaux qu'elle hérite de l'environnement où elle est définie (les coordonnées des points déjà calculés).

**Comment by lmoeneclaey** [comment]
J'étais occupé de clarifier le code mais j'ai donc changé mes variables comme vous me l'avez conseillé et cela marche bel et bien. Désolé de vous avoir autant dérangé pour une telle erreur mais je commençais à devenir fou. Merci beaucoup, bonne journée et bon week-end.

**Comment by lmoeneclaey** [comment]
Je voulais également vous prévenir que le dépôt était maintenant public. 
Bien cordialement,
Léopold

**Comment by boisgera** [comment]
OK, c'est noté !
